services:
  frontend:
    image: node:16
    container_name: housing_frontend
    volumes:
    - type: bind
      source: .
      target: /usr/src/app
      consistency: cached
    - frontend_node_modules:/usr/src/app/node_modules
    ports:
    - "3000:3000"
    working_dir: /usr/src/app
    command: npm start

volumes:
  frontend_node_modules:
    external: true