services:
  frontend:
    image: node:14
    container_name: housing_backend
    volumes:
    - type: bind
      source: .
      target: /usr/src/app
      consistency: cached
    - backend_node_modules:/usr/src/app/node_modules
    ports:
    - "8000:8000"
    working_dir: /usr/src/app
    command: nodemon ./bin/www

volumes:
  backend_node_modules:
    external: true