name: Deploy Backend to Heroku

on:
  push:
    branches: [ "master" ]
    paths: [ "backend/**" ]
  pull_request:
    branches: [ "master" ]
    paths: [ "backend/**" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "studenthousingwaterloo"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          appdir: backend
          branch: master
        env:
          ATLAS_URL: ${{secrets.ATLAS_URL}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_ACCESS_SECRET: ${{secrets.AWS_ACCESS_SECRET}}
          AWS_BUCKET_NAME: ${{secrets.AWS_BUCKET_NAME}}
          SESSION_SECRET: ${{secrets.SESSION_SECRET}}
